ui:
  title: Pagina de status Painel MMA
  logo: "https://pbs.twimg.com/profile_images/1727381913705336832/h4K-n1Nl_400x400.jpg"
  link: "https://www.labic.net/"
  header: Pagina de status Painel MMA
  description: Visualização do status de saúde do sistema
  dark-mode: false
  hide-url: true

endpoints:
  - name: Análise de sentimentos
    url: https://kumquat-greens-ant0oksb9ct039vh.salad.cloud
    interval: 30s
    conditions:
      - "[STATUS] == 200"
    ui:
      hide-url: true
  - name: Data Lake
    url: https://www.gologgo.com.br
    interval: 30s
    conditions:
      - "[STATUS] == 200"
