name: Deploy to VPS

on:
  push:
    branches:
      - main
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: SSH into VPS and pull latest changes
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USER }}
        key: ${{ secrets.VPS_SSH_KEY }}
        script: |
          cd pagina-status/Gatus-Status-Page/
          git pull
          cd run-status
          export $(grep -v '^#' .env | xargs) > /dev/null 2>&1
          envsubst < config.template.yaml > config.yaml
          
    - name: Docker stop and run
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USER }}
        key: ${{ secrets.VPS_SSH_KEY }}
        script: |
          if [ "$(docker ps -q -a -f name=gatus-status-page)" ]; then
          docker stop gatus-status-page
          docker rm gatus-status-page
          fi
          cd pagina-status/Gatus-Status-Page/run-status/
          docker run -d -p 8080:8080 --mount type=bind,source="$(pwd)"/config.yaml,target=/config/config.yaml --name gatus-status-page twinproduction/gatus